### PR TITLE
Tests that show EOFException (again)

### PR DESCRIPTION
**Pull request by kellyfj**
I forked again this morning (May 21st) and just added the tests and am able to reproduce the issue using the same instructions as before  (Turn off Wifi / Network, run test, it's fine, Turn on Wifi, run test, get Exception)

```
05-21 11:37:39.965    4615-4641/com.segment.analytics.core.test E/Segment﹕ Payloads were rejected by server. Marked for removal.
    com.segment.analytics.Client$UploadException: HTTP 400: Bad Request. Response: Could not read response body for rejected message: java.io.FileNotFoundException: https://api.segment.io/v1/import
            at com.segment.analytics.Client$1.close(Client.java:58)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:290)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:325)
            at com.segment.analytics.SegmentDispatcher.access$100(SegmentDispatcher.java:44)
            at com.segment.analytics.SegmentDispatcher$2.run(SegmentDispatcher.java:251)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
            at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:284)
05-21 11:37:40.175    4615-4637/com.segment.analytics.core.test E/Segment﹕ Error while uploading payloads
    java.io.EOFException
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:419)
            at com.segment.analytics.QueueFile.ringRead(QueueFile.java:255)
            at com.segment.analytics.QueueFile.readElement(QueueFile.java:176)
            at com.segment.analytics.QueueFile.forEach(QueueFile.java:422)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:283)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:325)
            at com.segment.analytics.SegmentDispatcher.access$100(SegmentDispatcher.java:44)
            at com.segment.analytics.SegmentDispatcher$2.run(SegmentDispatcher.java:251)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
            at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:284)
05-21 11:37:45.400      698-786/? D/PackageManager﹕ Sending to user 0: act=android.intent.action.PACKAGE_CHANGED dat=package:com.google.android.gms flg=0x8000000 Bundle[{android.intent.extra.DONT_KILL_APP=true, android.intent.extra.user_handle=0, android.intent.extra.changed_component_name_list=[Ljava.lang.String;@45c2fd20, android.intent.extra.UID=10060, android.intent.extra.changed_component_name=com.google.android.gms.checkin.CheckinService$ActiveReceiver}]
    java.lang.RuntimeException: It's not exception, just print call stack
            at com.android.server.pm.PackageManagerService.sendPackageBroadcast(PackageManagerService.java:7681)
            at com.android.server.pm.PackageManagerService.sendPackageChangedBroadcast(PackageManagerService.java:12493)
            at com.android.server.pm.PackageManagerService.access$300(PackageManagerService.java:224)
            at com.android.server.pm.PackageManagerService$PackageHandler.doHandleMessage(PackageManagerService.java:921)
            at com.android.server.pm.PackageManagerService$PackageHandler.handleMessage(PackageManagerService.java:721)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.os.HandlerThread.run(HandlerThread.java:61)
05-21 11:37:46.351    4743-4743/? W/System.err﹕ android.content.pm.PackageManager$NameNotFoundException: com.sec.android.cloudagent
05-21 11:38:07.351    4615-4637/com.segment.analytics.core.test E/Segment﹕ Error while uploading payloads
    java.io.EOFException
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:419)
            at com.segment.analytics.QueueFile.ringRead(QueueFile.java:255)
            at com.segment.analytics.QueueFile.readElement(QueueFile.java:176)
            at com.segment.analytics.QueueFile.forEach(QueueFile.java:422)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:283)
            at com.segment.analytics.SegmentDispatcher.access$100(SegmentDispatcher.java:44)
            at com.segment.analytics.SegmentDispatcher$2.run(SegmentDispatcher.java:251)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
            at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:284)
05-21 11:38:37.391    4615-4637/com.segment.analytics.core.test E/Segment﹕ Error while uploading payloads
    java.io.EOFException
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:419)
            at com.segment.analytics.QueueFile.ringRead(QueueFile.java:255)
            at com.segment.analytics.QueueFile.readElement(QueueFile.java:176)
            at com.segment.analytics.QueueFile.forEach(QueueFile.java:422)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:283)
            at com.segment.analytics.SegmentDispatcher.access$100(SegmentDispatcher.java:44)
            at com.segment.analytics.SegmentDispatcher$2.run(SegmentDispatcher.java:251)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:390)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
            at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:284)

```

### CODE REVIEW

**Comment by f2prateek** [comment]
@kellyfj Thanks! I can reproduce this intermittently. I don't see the application/crashing though, just exceptions in Logcat. Are you seeing the same behaviour?

**Comment by kellyfj** [comment]
Yes I concur - the current behavior is that my test passes and I just see the errors in LogCat.

**Comment by f2prateek** [comment]
Thanks, that's a partially good sign that it's not crashing the app at least.

The exception is being thrown because the `fileLength` stored in the header and the real file length are out of sync.

https://cloudup.com/cmBPZCA5jeA

Basically QueueFile thinks that the file has a much larger length than it actually does, causing it to read beyond the length of the file, resulting in the `EOFException`. I'm not entirely sure why this is happening. It's not during creation since there is a check for this condition so I suspect this happens sometime when we resize the file. 
```
if (fileLength > raf.length()) {
      throw new IOException("File is truncated. Expected length: " + fileLength + ", Actual length: " + raf.length());
}
```

**Comment by f2prateek** [comment]
@kellyfj Can you try the same test, but without instantiating multiple instances of the same analytics client? Here's the changes to be made - https://github.com/segmentio/analytics-android/commit/73bcccf89ea822651ecf7a1624e753245410afa9 - basically getting rid of the instantiation in the in the setup code and again in the test.

**Comment by f2prateek** [comment]
@kellyfj Please let me know if you see any warnings show up when you instantiate only one instance of the client.

**Comment by f2prateek** [comment]
I haven't been able to reproduce the issue with a single instance so this is what I suspect is happening. On the first run, we saturate the disk queue with events. Then on the second run, the analytics client will see that the QueueFile is very large and start uploading events. Since the test initializes two instances of the client, both are now trying to upload events from the same file. At some point, client A will upload events, remove them and shrink the size of the QueueFile. But client B keeps a cached copy of QueueFile's file length, and it doesn't realize that the QueueFile has shrunk (and it doesn't need need to, since only analytics client should interact with the same QueueFile at any given time) and tries to beyond the bounds of the QueueFile, resulting in the EOFException.

The solution is to ensure only one analytics client is created per write key. if you need multiple, then you can set a tag in the Analytics Builder.

**Pull request closed without merging**
