### PR TITLE
Add Segment integration for Apptimize

### PR DESCRIPTION
**Pull request by f2prateek**

### CODE REVIEW

**Comment by confiscate** [comment]
feel free to merge this

**Comment by f2prateek** [comment]
@confiscate we're just waiting on adding Apptimize as an integration on our dashboard, this will be merged shortly after.

**Comment by confiscate** [comment]
cool. do you need anything from us in terms of Logo icons or documentation text etc?

**Comment by f2prateek** [comment]
I think we should have everything from the technical and business survey. If not, @amillet89 or @samdup will reach out.

**Comment by amillet89** [comment]
@confiscate ready to add you guys but we would need logo and docs file (similar to https://gist.github.com/amillet89/e59d2a329cd8bf1151a2) sent to testing+apptimize@segment.com as per technical survey. thanks!

**Comment by confiscate** [comment]
adding mike, Head of Product from apptimize

@mpoon

**Pull request merged**
