### PR TITLE
export CIRCLE_JDK_VERSION in CI build so we can deploy snapshots

### PR DESCRIPTION
**Pull request by f2prateek**

### CODE REVIEW

**Comment by brennan** [comment]
@f2prateek It looks as if this PR fails with numerous errors. I can't figure out why that would occur given that you only updated one line. I see similar errors for the `build-update` branch. Given that the changes in the two branches are not the same, it is strange that Circle would throw many of the same errors. Could this be either a Circle issue, or a situation where an Android repo is temporarily unavailable, resulting in "package...does not exist" errors?

Circle also reports lint errors for this branch. Is it possible this is because Circle is now testing analytics-android again Java 8-specific styles?

**Comment by ladanazita** [comment]
The script is just setup to fail if any warnings surface. Rebuild with ssh and ran `./gradlew checkFmt build --stacktrace` and see that the CI script is failing on warnings, which we could update to ignore. 

```
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
```

Complete stack trace:

```
Ran lint on variant debug: 10 issues found
/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java:274: Error: Missing permissions required by ConnectivityManager.getNetworkInfo: android.permission.ACCESS_NETWORK_STATE [MissingPermission]
        NetworkInfo wifiInfo = connectivityManager.getNetworkInfo(TYPE_WIFI);
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java:276: Error: Missing permissions required by ConnectivityManager.getNetworkInfo: android.permission.ACCESS_NETWORK_STATE [MissingPermission]
        NetworkInfo bluetoothInfo = connectivityManager.getNetworkInfo(TYPE_BLUETOOTH);
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/AnalyticsContext.java:278: Error: Missing permissions required by ConnectivityManager.getNetworkInfo: android.permission.ACCESS_NETWORK_STATE [MissingPermission]
        NetworkInfo cellularInfo = connectivityManager.getNetworkInfo(TYPE_MOBILE);
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/internal/Utils.java:268: Error: Missing permissions required by TelephonyManager.getDeviceId: android.permission.READ_PHONE_STATE [MissingPermission]
      String telephonyId = telephonyManager.getDeviceId();
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/internal/Utils.java:307: Error: Missing permissions required by ConnectivityManager.getActiveNetworkInfo: android.permission.ACCESS_NETWORK_STATE [MissingPermission]
    NetworkInfo activeNetwork = cm.getActiveNetworkInfo();
                                ~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "MissingPermission":
   This check scans through your code and libraries and looks at the APIs
   being used, and checks this against the set of permissions required to
   access those APIs. If the code using those APIs is called at runtime, then
   the program will crash.

   Furthermore, for permissions that are revocable (with targetSdkVersion 23),
   client code must also be prepared to handle the calls throwing an exception
   if the user rejects the request for permission at runtime.

/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/internal/Utils.java:252: Warning: Using getString to get device identifiers is not recommended. [HardwareIds]
    String androidId = getString(context.getContentResolver(), ANDROID_ID);
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/internal/Utils.java:261: Warning: Using SERIAL to get device identifiers is not recommended. [HardwareIds]
    if (!isNullOrEmpty(Build.SERIAL)) {
                             ~~~~~~
/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/internal/Utils.java:262: Warning: Using SERIAL to get device identifiers is not recommended. [HardwareIds]
      return Build.SERIAL;
                   ~~~~~~
/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/internal/Utils.java:268: Warning: Using getDeviceId to get device identifiers is not recommended. [HardwareIds]
      String telephonyId = telephonyManager.getDeviceId();
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "HardwareIds":
   Using these device identifiers is not recommended other than for high value
   fraud prevention and advanced telephony use-cases. For advertising
   use-cases, use AdvertisingIdClient$Info#getId and for analytics, use
   InstanceId#getId.

   https://developer.android.com/training/articles/user-data-ids.html

/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/Analytics.java:111: Warning: Do not place Android context classes in static fields (static reference to Analytics which has field application pointing to Application); this is a memory leak (and also breaks Instant Run) [StaticFieldLeak]
  static volatile Analytics singleton = null;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "StaticFieldLeak":
   A static field will leak contexts.

5 errors, 5 warnings
Wrote HTML report to file:///home/circleci/analytics-android/analytics/build/reports/lint-results.html
Wrote XML report to file:///home/circleci/analytics-android/analytics/build/reports/lint-results.xml
:analytics:lint FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':analytics:lint'.
> Lint found errors in the project; aborting build.

  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
```

**Comment by f2prateek** [comment]
> @f2prateek It looks as if this PR fails with numerous errors. It looks like there may be something wrong with the circle ci 2.0 yml file configuration.

If you are referring to these errors:

```
                                 ^
/home/circleci/analytics-android/analytics/src/main/java/com/segment/analytics/integrations/TrackPayload.java:32: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
```

Then that's expected, you can see them in the pre-Circle 2.0 builds as well.

> Ah it's coming from these changes I believe, but this seems intentional since you are adding better annotations to catch bugs in this lib, yeah?


I didn't merge https://github.com/segmentio/analytics-android/pull/556/files yet, so shouldn't be because of that.

Don't think it's clear from the build why it failed, likely will have to run it with the debug option and see.

**Comment by f2prateek** [comment]
Think it was just a flaky error. Rebuilding fixed it.

**Pull request merged**
