### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by mbernier85**
* First I updated to latest android sdk version 28
* Updated Java to compile with version 8 bytecode
* Then run migration to AndroidX

The goal is to allow user of the library to disable Jetifier

The only library causing issues here was the Annotation lib

I also updated Butterknife to 10, so it can use AndroidX

Some test lib were also updated in the migration

### CODE REVIEW

**Comment by f2prateek** [comment]
The CI is failing: "> com.android.builder.testing.api.DeviceException: No connected devices!"

**Comment by mbernier85** [comment]
> The CI is failing: "> com.android.builder.testing.api.DeviceException: No connected devices!"

Is there something I should be trying to fix here, because I honestly have no idea how your setup for Instrumentation test is done ...

**Comment by f2prateek** [comment]
We just won't be able to merge the PR until that the CI is fixed. The CI is green on master, so I am assuming something in these changes broke it.

**Comment by mbernier85** [comment]
> We just won't be able to merge the PR until that the CI is fixed. The CI is green on master, so I am assuming something in these changes broke it.

It looks like a bug in one of the plugins for Jacoco https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/issues/147

was this task running before?

**Comment by egor-n** [comment]
What are the plans with AndroidX migration of the SDK?

**Comment by felipearosemena** [comment]
Any update on this?

**Comment by chrisjenx** [comment]
What needs to doing to get this merged and released?

**Comment by lordcodes** [comment]
It was said further up, that this couldn't be merged until CI was passing.
If the original author of the PR isn't available to look into it, I guess someone could make their own version and get CI passing.

If CI was failing due to some change with JaCoCo maybe there could be a PR that only makes the required changes to switch to AndroidX.

**Comment by chrisjenx** [comment]
@colinrtwhite maybe we  should we take a look into this next week? CI seems like a small blocker.

**Comment by lordcodes** [comment]
> @colinrtwhite maybe we should we take a look into this next week? CI seems like a small blocker.

I created a new PR #658 that performs the AndroidX update, as well as updating all the tooling and samples to latest versions. Due to this one having been inactive for nearly a year.

**Comment by bsneed** [comment]
Closing in favor of #658

**Pull request closed without merging**
