### PR TITLE
Add support for incrementing customer value in Localytics

### PR DESCRIPTION
**Pull request by sperand-io**
not sure if this is the correct way of handling just yet... but this is a first crack at adding support for customer LTV in localytics, a la: http://docs.localytics.com/index.html#Dev/Instrument/customer-ltv.html

iOS parity, for reference: https://github.com/segmentio/analytics-ios/blob/master/Analytics/Integrations/Localytics/SEGLocalyticsIntegration.m#L127-L134

### CODE REVIEW

**Comment by f2prateek** [comment]
I think this is a dupe of #303. We just need tests in that one of you want to take that on.

The CI error is from using properties instead of props as the variable name.

**Comment by sperand-io** [comment]
aha! should have caught both of those things. thanks @f2prateek!

**Comment by f2prateek** [comment]
Changed it to use cents

**Comment by sperand-io** [comment]
perfect — thanks!

**Pull request merged**
