### PR TITLE
Taplytics Version Up

### PR DESCRIPTION
**Pull request by VicV**

### CODE REVIEW

**Comment by f2prateek** [comment]
You'll have to update the reference in the `build.gradle` file as well  - https://github.com/segmentio/analytics-android/blob/master/analytics-integrations/taplytics/build.gradle#L4.

Also please leave the jar name starting with caps `Taplytics-...` instead of `taplytics-...`

**Comment by f2prateek** [comment]
You can run `./gradlew build` from the command line to verify everything builds as well.

**Comment by VicV** [comment]
righto

**Comment by VicV** [comment]
All set @f2prateek

**Pull request closed without merging**
